# Generated by Django 5.2.5 on 2025-11-21 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AddField(
            model_name='postpurchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_purchase', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='postpurchase',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='blog.post'),
        ),
        migrations.AddField(
            model_name='postpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_at', '-created_at'], name='post_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'is_published', '-published_at'], name='post_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'is_published'], name='post_author_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='comment_post_date_idx'),
        ),
        migrations.AddIndex(
            model_name='postpurchase',
            index=models.Index(fields=['user', 'status'], name='purchase_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postpurchase',
            index=models.Index(fields=['user', 'post'], name='purchase_user_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postpurchase',
            index=models.Index(fields=['post', 'status'], name='purchase_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postpurchase',
            index=models.Index(fields=['payment'], name='purchase_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='postpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('user', 'post'), name='unique_successful_purchase_per_post'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='reaction_post_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'user')},
        ),
    ]
