import os

# Payment topics
PAYMENTS_REQUEST = os.environ['KAFKA_TOPIC_PAYMENTS_REQUEST']
PAYMENTS_COMPLETED = os.environ['KAFKA_TOPIC_PAYMENTS_COMPLETED']
PAYMENTS_CANCELLED = os.environ['KAFKA_TOPIC_PAYMENTS_CANCELLED']

# Subscription topics
SUBSCRIPTIONS_REQUEST = os.environ['KAFKA_TOPIC_SUBSCRIPTIONS_REQUEST']
SUBSCRIPTIONS_COMPLETED = os.environ['KAFKA_TOPIC_SUBSCRIPTIONS_COMPLETED']
SUBSCRIPTIONS_CANCELLED = os.environ['KAFKA_TOPIC_SUBSCRIPTIONS_CANCELLED']
